name: holidaycard.shop CI/CD

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - name: copy file via ssh
              uses: garygrossgarten/github-action-scp@master
              with:
                  host: allchat.online
                  username: ubuntu
                  privateKey: ${{ secrets.DEPLOY_KEY }}
                  local: './docker-compose.yml'
                  remote: 'holiday/docker-compose.yml'

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Build frontend
              run: bun run build

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@master

            - name: Log in to Docker Hub
              uses: docker/login-action@master
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Backend Image (arm64)
              run: |
                  docker buildx build \
                  --platform linux/arm64/v8 \
                  --output "type=image,push=true" \
                  --tag ${{ secrets.DOCKER_USERNAME }}/holiday \
                  .

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to SSH Host
              env:
                  SSH_KEY: ${{ secrets.DEPLOY_KEY }}
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H allchat.online >> ~/.ssh/known_hosts
                  ssh ubuntu@allchat.online '
                    docker pull ${{ secrets.DOCKER_USERNAME }}/holiday
                    cd holiday
                    docker-compose down
                    docker-compose up -d
                  '
